apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    tier: app
    env: dev
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
      env: dev
      project: roboshop

  template:
    metadata:
      labels: 
        tier: app
        env: dev
        project: roboshop

    spec:
      containers:
      - name: payment
        image: surajk879/payment:1.7
        envFrom:
        - configMapRef:
            name: payment

---

apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop

spec:
  selector:
    tier: app
    env: dev
    project: roboshop

  ports:
  - name: payment
    protocol: TCP
    port: 8080
    targetPort: 8080


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop

data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"