apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    tier: app
    env: dev
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
      env: dev
      project: roboshop

  template:
    metadata:
      labels:
        tier: app
        env: dev
        project: roboshop

    spec:
      containers:
      - name: payment
        image: surajk879/payment:1.7
        envFrom:
        - configMapRef:
            name: payment