apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    tier: app
    env: dev
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
      env: dev
      project: roboshop

  template:
    metadata:
      labels:
        tier: app
        env: dev
        project: roboshop

    spec:
      containers:
      - name: shipping
        image: surajk879/shipping:1.7
        envFrom:
        - configMapRef:
            name: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop

spec:
  selector:
    tier: app
    env: dev
    project: roboshop

  ports:
  - name: shipping
    protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop

data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"