apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    env: dev
    tier: db
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      tier: db
      project: roboshop

  template:
    metadata:
      env: dev
      tier: db
      project: roboshop

    spec:
      containers:
      - name: mysql
        image: surajk879/mysql:1.7
        imagepUllPolicy: Always
        envFrom:
        - configMapRef:
            name: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop

spec:
  selector:
    env: dev
    tier: db
    project: roboshop

  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop

data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
  MYSQL_DATABASE: "cities" 
  MYSQL_USER: "shipping" 
  MYSQL_PASSWORD: "RoboShop@1"