apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    tier: app
    env: dev
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
      env: dev
      project: roboshop

  template:
    metadata:
      labels:
        tier: app
        env: dev
        project: roboshop

    spec:
      containers:
      - name: user
        image: surajk879/user:1.7
        envFrom:
        - ConfigMapRef:
            name: user

---

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop

spec:
  selector:
    tier: app
    env: dev
    project: roboshop

  ports:
  - name: user
    protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop

data:
  MONGO: "true"
  REDIS_HOST: "redis"
  MONGO_URL: "mongodb://mongodb:27017/users"

  